version: '3.8'

services:
    python:
        build:
            context: . 
            dockerfile: docker/python/Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - ./src:/workspace
